# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'flixster' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '5.5.0'
  pod 'AlamofireImage', '4.2.0'
  pod 'SwiftyJSON', '~> 4.0'

  # Pods for flixster

  target 'flixsterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'flixsterUITests' do
    # Pods for testing
  end

end
